project_id = "sszlrehkyqdqwuojobej"

[functions.connect-meta-token]
verify_jwt = false

[functions.connect-google-token]
verify_jwt = false

[functions.oauth-google]
verify_jwt = false

[functions.oauth-meta]
verify_jwt = false

[functions.check-balance-alerts]
verify_jwt = false

[functions.generate-report]
verify_jwt = false
